# Permalinks
permalink:           pretty

# Setup
title:               The Dividend Nerd
tagline:             A blog about becoming a dividend nerd
url:                 tvbrux.github.io
baseurl:             
analytics_id:

# Owner/author information
owner:
  name:           Thijs
  avatar:         avatar.png
  bio:            "Aspiring dividend nerd."
  email:          thijs@brux.nl
  #twitter:        alexanderussell
  github:         tvbrux       
  location:       "Utrecht, NL"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
